# Generated by Django 5.2.10 on 2026-02-21 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("nivel", models.PositiveIntegerField(default=1)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "dificultad",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("avanzado", "Avanzado"),
                            ("dificil", "Dificil"),
                            ("pro", "Pro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zonas_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zonas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zona",
                "verbose_name_plural": "Zonas",
                "db_table": "zona",
                "ordering": ["nivel", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Enemigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("normal", "Normal"), ("jefe", "Jefe")], max_length=20
                    ),
                ),
                (
                    "rareza",
                    models.CharField(
                        choices=[
                            ("comun", "Comun"),
                            ("raro", "Raro"),
                            ("epico", "Epico"),
                            ("legendario", "Legenario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("vida_maxima", models.PositiveIntegerField(default=10)),
                ("ataque", models.PositiveIntegerField(default=5)),
                ("defensa", models.PositiveIntegerField(default=2)),
                ("velocidad", models.PositiveIntegerField(default=3)),
                ("exp_otorgada", models.PositiveIntegerField(default=10)),
                ("oro_otorgado", models.PositiveIntegerField(default=0)),
                (
                    "creada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enemigos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enemigos",
                        to="juego.zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enemigo",
                "verbose_name_plural": "Enemigos",
                "ordering": ["zona", "tipo", "nombre"],
            },
        ),
    ]
