# Generated by Django 5.2.11 on 2026-02-20 12:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('consumible', 'Consumible'), ('equipable', 'Equipable')], max_length=20)),
                ('rareza', models.CharField(choices=[('comun', 'Comun'), ('raro', 'Raro'), ('epico', 'Epico'), ('legendario', 'Legendario')], max_length=20)),
                ('efecto', models.TextField()),
                ('valor_venta', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('slot', models.CharField(blank=True, choices=[('arma', 'Arma'), ('armadura', 'Armadura'), ('accesorio', 'Accesorio')], max_length=20, null=True)),
                ('bonus_ataque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus_defensa', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus_salud', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus_velocidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
                'ordering': ['rareza', 'nombre'],
                'indexes': [models.Index(fields=['tipo'], name='juego_objet_tipo_22cf17_idx'), models.Index(fields=['rareza'], name='juego_objet_rareza_26ae94_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_venta__gte', 0)), name='valor_no_negativo'), models.CheckConstraint(condition=models.Q(models.Q(models.Q(('slot__isnull', False), ('tipo', 'equipable')), models.Q(('slot__isnull', True), ('tipo', 'consumible')), _connector='OR')), name='consumible_no_tiene_slot')],
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nivel', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('exp_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ataque', models.IntegerField(default=10)),
                ('defensa', models.IntegerField(default=10)),
                ('salud_maxima', models.IntegerField(default=50)),
                ('vida_actual', models.IntegerField(default=50)),
                ('velocidad', models.IntegerField(default=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('equipado', models.BooleanField(default=False)),
                ('posicion_slot', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_adquisicion', models.DateTimeField(auto_now_add=True)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_inventarios', related_query_name='en_inventario', to='juego.objeto')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_items', related_query_name='inventario_item', to='juego.personaje')),
            ],
            options={
                'verbose_name': 'Item de Inventario',
                'verbose_name_plural': 'Items de Inventario',
                'ordering': ['-equipado', '-fecha_adquisicion'],
            },
        ),
        migrations.AddIndex(
            model_name='personaje',
            index=models.Index(fields=['usuario', 'nombre'], name='juego_perso_usuario_c902dd_idx'),
        ),
        migrations.AddIndex(
            model_name='personaje',
            index=models.Index(fields=['usuario', '-nivel'], name='juego_perso_usuario_811c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='personaje',
            index=models.Index(fields=['estado'], name='juego_perso_estado_b6e243_idx'),
        ),
        migrations.AddConstraint(
            model_name='personaje',
            constraint=models.CheckConstraint(condition=models.Q(('nivel__gte', 1), ('nivel__lte', 100)), name='nivel_valido'),
        ),
        migrations.AddConstraint(
            model_name='personaje',
            constraint=models.CheckConstraint(condition=models.Q(('exp_actual__gte', 0)), name='exp_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='personaje',
            constraint=models.CheckConstraint(condition=models.Q(('vida_actual__gte', 0)), name='vida_actual_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='personaje',
            constraint=models.CheckConstraint(condition=models.Q(('vida_actual__lte', models.F('salud_maxima'))), name='vida_no_supera_maxima'),
        ),
        migrations.AlterUniqueTogether(
            name='personaje',
            unique_together={('usuario', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['personaje', 'equipado'], name='juego_inven_persona_08bcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['personaje', '-fecha_adquisicion'], name='juego_inven_persona_b7366d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['objeto'], name='juego_inven_objeto__785c23_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='cantidad_minima_uno'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equipado', False), models.Q(('equipado', True), ('posicion_slot__isnull', False)), _connector='OR')), name='equipado_requiere_slot'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('personaje', 'objeto')},
        ),
    ]
