# Generated by Django 5.2.11 on 2026-02-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-equipado', '-fecha_adquisicion'], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventario'},
        ),
        migrations.RemoveIndex(
            model_name='inventario',
            name='juego_inven_persona_08bcb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventario',
            name='juego_inven_persona_b7366d_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventario',
            name='juego_inven_objeto__785c23_idx',
        ),
        migrations.RemoveIndex(
            model_name='objeto',
            name='juego_objet_tipo_22cf17_idx',
        ),
        migrations.RemoveIndex(
            model_name='objeto',
            name='juego_objet_rareza_26ae94_idx',
        ),
        migrations.RemoveIndex(
            model_name='personaje',
            name='juego_perso_usuario_c902dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='personaje',
            name='juego_perso_usuario_811c0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='personaje',
            name='juego_perso_estado_b6e243_idx',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='posicion_slot',
            field=models.CharField(blank=True, choices=[('arma', 'Arma'), ('armadura', 'Armadura'), ('accesorio', 'Accesorio')], max_length=20, null=True),
        ),
    ]
