# Generated by Django 5.2.7 on 2026-02-27 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_zona_enemigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('jefe', 'Jefe')], default='normal', max_length=10)),
                ('resultado', models.CharField(blank=True, choices=[('victoria', 'Victoria'), ('derrota', 'Derrota'), ('huida', 'Huida')], max_length=20, null=True)),
                ('exp_ganada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('botin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combates_dropeados', to='juego.objeto')),
                ('enemigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates', related_query_name='combate', to='juego.enemigo')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates', related_query_name='combate', to='juego.personaje')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combates', to='juego.zona')),
            ],
            options={
                'verbose_name': 'Combate',
                'verbose_name_plural': 'Combates',
                'db_table': 'juego_combate',
                'ordering': ['-fecha_hora'],
                'constraints': [models.CheckConstraint(condition=models.Q(('exp_ganada__gte', 0)), name='exp_ganada_no_negativa')],
            },
        ),
    ]
