# Generated by Django 5.2.11 on 2026-02-28 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_combate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personaje',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('usuario',), name='usuario_un_personaje'),
        ),
    ]
