# Generated by Django 5.2.11 on 2026-02-28 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0005_personaje_usuario_un_personaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='exp_actual',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
