# Generated by Django 5.2.11 on 2026-02-28 12:00

from django.db import migrations


def calcular_niveles(apps, schema_editor):
    """Recalcula los niveles de todos los personajes basándose en su experiencia."""
    Personaje = apps.get_model('juego', 'Personaje')
    for personaje in Personaje.objects.all():
        # Fórmula: Nivel = (exp_actual // 100) + 1, máximo 100
        personaje.nivel = min((personaje.exp_actual // 100) + 1, 100)
        personaje.save(update_fields=['nivel'])


def deshacer_calculos(apps, schema_editor):
    """Este cambio no se puede deshacer de forma reversible."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_alter_personaje_exp_actual'),
    ]

    operations = [
        migrations.RunPython(calcular_niveles, deshacer_calculos),
    ]
