# Generated by Django 5.2.11 on 2026-02-28 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0007_recalcular_niveles_desde_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='curacion_vida',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
